project 'SwiftLearning.xcodeproj'

platform :ios, '15.0'
use_frameworks!

target 'SwiftLearning' do
#  pod 'Google-Mobile-Ads-SDK', '~> 10.12.0'

  post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
end
#
#target 'Swift-TV' do
#  post_install do |installer|
#    installer.pods_project.build_configurations.each do |config|
#      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
#    end
#  end
#end
#
